@PORT = 3000
@HOST = http://localhost:{{PORT}}
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3MTU4ODE0NjQsImlhdCI6MTcxNTI3NjY2NH0.FbTCDm2woXCkqHMJccs6-4ocoynaPKDMg7dVBCJEGqo

### REGISTRAR UN USUARIO
POST {{HOST}}/api/usuarios/register
Content-Type: application/json

{
  "name": "Miguel",
  "lastname": "Eguiguren",
  "email": "miguel@example.com",
  "photo": "",
  "password": "password123"
}

### Iniciar sesión
POST {{HOST}}/api/usuarios/login
Content-Type: application/json

{
  "email": "juan.perez@example.com",
  "password": "password123"
}

### OBTENER TODOS LOS USUARIOS
GET {{HOST}}/api/usuarios

### Obtener un usuario por ID
GET {{HOST}}/api/usuarios/1


### Actualizar un usuario
PUT {{HOST}}/api/usuarios/3
Content-Type: application/json

{
  "name": "Miguel Actualizado",
  "lastname": "Eguiguren Actualizado",
  "email": "miguel.eguiguren@example.com",
  "photo": null,
  "password": "nuevaPassword123"
}

### Eliminar un usuario
DELETE {{HOST}}/api/usuarios/3


-----------------------------------------------

### Crear un grupo
POST {{HOST}}/api/grupos
Content-Type: application/json

{
  "title": "Viaje a la playa",
  "description": "Gastos del viaje a la playa"
}

### Obtener todos los grupos
GET {{HOST}}/api/grupos

### Obtener un grupo por ID
GET {{HOST}}/api/grupos/6

### Actualizar un grupo
PUT {{HOST}}/api/grupos/6
Content-Type: application/json

{
  "title": "Viaje a la montaña",
  "description": "Gastos del viaje a la montaña"
}

### Eliminar un grupo
DELETE {{HOST}}/api/grupos/6

--------------------------------------------------------------
### Crear un gasto
POST {{HOST}}/api/gastos
Content-Type: application/json

{
  "group_id": 1,
  "amount": 100.00,
  "description": "Compra de alimentos"
}

### Obtener todos los gastos
GET {{HOST}}/api/gastos

### Obtener un gasto por ID
GET {{HOST}}/api/gastos/1

### Actualizar un gasto
PUT {{HOST}}/api/gastos/1
Content-Type: application/json

{
  "group_id": 1,
  "amount": 150.00,
  "description": "Compra de alimentos y bebidas"
}

### Eliminar un gasto
DELETE {{HOST}}/api/gastos/1

------------------------------------------------------------------------

### Crear un pago
POST {{HOST}}/api/pagos
Content-Type: application/json

{
  "expense_id": 1,
  "user_id": 1,
  "amount_paid": 50.00
}

### Obtener todos los pagos
GET {{HOST}}/api/pagos

### Obtener un pago por ID
GET {{HOST}}/api/pagos/1

### Actualizar un pago
PUT {{HOST}}/api/pagos/1
Content-Type: application/json

{
  "expense_id": 1,
  "user_id": 1,
  "amount_paid": 75.00
}

### Eliminar un pago
DELETE {{HOST}}/api/pagos/1
